# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 8810:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8811:8080
